# -*- coding: utf-8 -*-
"""광진구_자양동_최종코드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PB7RP8f407t8bb4LQ3eAdSzMcu18HBN6
"""

!pip install haversine
!pip install -U googlemaps
!pip install folium

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import folium

data = pd.read_csv('/content/drive/MyDrive/EGG_광진/코드/서울시 광진구 일반음식점 인허가 정보.csv', encoding='cp949')
print(data.head())

data1 = data[data['상세영업상태코드'] == 1]
data1

for i in range(data1.shape[0]):
    print(data1.iloc[i]['지번주소'], data1.iloc[i]['좌표정보(X)'], data1.iloc[i]['좌표정보(Y)'])

import folium

# 위도
latitude = 37.55573889
# 경도
longitude = 127.0845333
m = folium.Map(location=[latitude, longitude],
               zoom_start=13,
               width=750,
               height=500
              )
m

import pandas as pd
import numpy as np
import pyproj

data1['좌표정보(X)'] = pd.to_numeric(data1['좌표정보(X)'], errors="coerce")
data1['좌표정보(Y)'] = pd.to_numeric(data1['좌표정보(Y)'], errors="coerce")

data1.dropna(subset=['좌표정보(X)', '좌표정보(Y)'], inplace=True)
data1.index = range(len(data1))

def project_array(coord, p1_type, p2_type):
    """
    좌표계 변환 함수
    - coord: x, y 좌표 정보가 담긴 NumPy Array
    - p1_type: 입력 좌표계 정보 ex) epsg:5174
    - p2_type: 출력 좌표계 정보 ex) epsg:3857
    """
    p1 = pyproj.Proj(init=p1_type)
    p2 = pyproj.Proj(init=p2_type)
    fx, fy = pyproj.transform(p1, p2, coord[:, 0], coord[:, 1])
    return np.dstack([fx, fy])[0]

coord = np.array(data1[['좌표정보(X)', '좌표정보(Y)']])
print(coord)

# 컬럼 좌표(X) 또는 좌표(Y) 중의 값이 하나라도 없으면 변환이 안 되는 조건 추가
if len(coord) == 0:
    print("No valid coordinates found. Transformation cannot be performed.")
else:
    # 좌표계 정보 설정
    p1_type = "epsg:5174"
    p2_type = "epsg:3857"

    # project_array() 함수 실행
    result = project_array(coord, p1_type, p2_type)
    print(result)

    data1['경도X'] = result[:, 0]
    data1['위도Y'] = result[:, 1]

    data1.tail()
    output_file = '/content/drive/MyDrive/EGG_광진/서울시 광진구 일반음식점 인허가 정보_1.csv'
    data1.to_csv(output_file, index=False, encoding='utf-8')

df = pd.read_csv('/content/drive/MyDrive/EGG_광진/서울시 광진구 일반음식점 인허가 정보_1.csv', encoding='utf-8')

df['경도X'] = pd.to_numeric(df['경도X'], errors="coerce")
df['위도Y'] = pd.to_numeric(df['위도Y'], errors="coerce")

df.dropna(subset=['경도X', '위도Y'], inplace=True)
df.index = range(len(df))

def project_array(coord, p1_type, p2_type):
    """
    좌표계 변환 함수
    - coord: x, y 좌표 정보가 담긴 NumPy Array
    - p1_type: 입력 좌표계 정보 ex) epsg:4326
    - p2_type: 출력 좌표계 정보 ex) epsg:3857
    """
    p1 = pyproj.Proj(init=p1_type)
    p2 = pyproj.Proj(init=p2_type)
    fx, fy = pyproj.transform(p1, p2, coord[:, 0], coord[:, 1])
    return np.dstack([fx, fy])[0]

coord = np.array(df[['경도X', '위도Y']])
print(coord)

# 컬럼 좌표(X) 또는 좌표(Y) 중의 값이 하나라도 없으면 변환이 안 되는 조건 추가
if len(coord) == 0:
    print("No valid coordinates found. Transformation cannot be performed.")
else:
    # 좌표계 정보 설정
    p1_type = "EPSG:3857"
    p2_type = "EPSG:4326"

    # project_array() 함수 실행
    result = project_array(coord, p1_type, p2_type)
    print(result)

    df['경도'] = result[:, 0]
    df['위도'] = result[:, 1]

    df.tail()

    output_file = '/content/drive/MyDrive/EGG_광진/서울시 광진구 일반음식점 인허가 정보_2.csv.csv'
    df.to_csv(output_file, index=False, encoding='utf-8')

df.head()

df2 = df.copy()
df2 = df2[['지번주소', '위도', '경도']]


# 서울특별시 광진구 제거
df2['지번주소'] = df2['지번주소'].str.replace('서울특별시 광진구', '')

# 특수문자 ('-') 제거
df2['지번주소'] = df2['지번주소'].str.replace(pat = r'[^\w]', repl = r'', regex = True)

# 숫자 제거
df2['지번주소'] = df2['지번주소'].str.replace(pat = r"[0-9]+", repl = r'', regex = True)

# '동' 제외 문자 제거
r = r'(?<=동).*$'
df2['지번주소'] = df2['지번주소'].str.replace(pat = r, repl = '', regex = True)

# 공백 제거 확인
df2['지번주소'] = df2['지번주소'].replace(r'^\s+|\s+$', '', regex = True)

df2

jayang = df2[df2['지번주소'] == '자양동']
jayang

import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon

# 자양동
jayang_dong_polygon = Polygon([(127.064266, 37.542486), (127.083535, 37.536838),
                                   (127.088168, 37.528348), (127.059480, 37.533899)])

# 코랩에 지도를 표시합니다
m = folium.Map(location=[37.543170, 127.073432], zoom_start=13)

# 양동의 경계를 Polygon으로 표시합니다
folium.GeoJson(jayang_dong_polygon).add_to(m)

m

import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon

# 자양동
jayang_dong_polygon = Polygon([(127.064266, 37.542486), (127.083535, 37.536838),
                                   (127.088168, 37.528348), (127.059480, 37.533899)])

# 코랩에 지도를 표시합니다
m = folium.Map(location=[37.543170, 127.073432], zoom_start=13)

# 자양동의 경계를 Polygon으로 표시합니다
folium.GeoJson(jayang_dong_polygon).add_to(m)

# MarkerCluster 객체를 생성합니다
marker_cluster = MarkerCluster()

# 화양동을 중심으로 마커를 추가합니다
folium.Marker([37.531692, 127.074516], popup="자양동").add_to(marker_cluster)

# MarkerCluster를 지도에 추가합니다
marker_cluster.add_to(m)


for i in jayang.index[::]:
    folium.Circle(
        location = jayang.loc[i, ['위도', '경도']],
        tooltip = jayang.loc[i, '지번주소'],
        radius = 1
    ).add_to(m)


# 지도를 표시합니다
m

import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon

# 자양동
jayang_dong_polygon = Polygon([(127.064266, 37.542486), (127.083535, 37.536838),
                                   (127.088168, 37.528348), (127.059480, 37.533899)])

# 코랩에 지도를 표시합니다
m = folium.Map(location=[37.543170, 127.073432], zoom_start=13)

# 후보지점 (랜덤 생성)
np.random.seed(42)
df_candidates = pd.DataFrame({
    'latitude': np.random.uniform(37.528348, 37.542486, 100),
    'longitude': np.random.uniform(127.059480, 127.088168, 100)
})

# 모든 후보지 시각화
for idx, candidate in df_candidates.iterrows():
    folium.CircleMarker(
        location=[candidate['latitude'], candidate['longitude']],
        radius=5,
        color='red',
        fill=True,
        fill_color='red'
    ).add_to(m)


# 양동의 경계를 Polygon으로 표시합니다
folium.GeoJson(jayang_dong_polygon).add_to(m)

m

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import folium

def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    d = R * c
    return d
# 수요지점
df_demand=jayang

# 후보지점 (랜덤 생성)
np.random.seed(42)
df_candidates = pd.DataFrame({
    'latitude': np.random.uniform(37.528348, 37.542486, 100),
    'longitude': np.random.uniform(127.059480, 127.088168, 100)
})

k = 40
kmeans = KMeans(n_clusters=k, n_init=20, random_state=0).fit(df_demand[['위도', '경도']])
centers = kmeans.cluster_centers_


selected_candidates_idx = []
unused_candidate_idxs = set(df_candidates.index)  # 사용하지 않은 후보지점의 인덱스를 저장하는 집합

for center in centers:
    closest_distance = np.inf
    closest_idx = None
    for idx in unused_candidate_idxs:  # 사용되지 않은 후보지점만 고려
        candidate = df_candidates.loc[idx]
        distance = haversine(center[0], center[1], candidate['latitude'], candidate['longitude'])
        if distance < closest_distance:
            closest_distance = distance
            closest_idx = idx

    if closest_idx is not None:  # 가장 가까운 후보지점을 찾았다면
        selected_candidates_idx.append(closest_idx)
        unused_candidate_idxs.remove(closest_idx)  # 선택된 후보지점을 사용된 것으로 표시

map_center_latitude = df_demand.iloc[0]['위도']
map_center_longitude = df_demand.iloc[0]['경도']
m = folium.Map(location=[map_center_latitude, map_center_longitude], zoom_start=12)

# 수요 지점 시각화
for idx, row in df_demand.iterrows():
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=5,
        color='blue',
        fill=True,
        fill_color='blue'
    ).add_to(m)

# 선택된 후보지 시각화 - 별 모양으로
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon = folium.Icon(icon='cloud')
    ).add_to(m)

# 모든 후보지 시각화
for idx, candidate in df_candidates.iterrows():
    folium.CircleMarker(
        location=[candidate['latitude'], candidate['longitude']],
        radius=5,
        color='red',
        fill=True,
        fill_color='red'
    ).add_to(m)


import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon

# 자양동
jayang_dong_polygon = Polygon([(127.064266, 37.542486), (127.083535, 37.536838),
                                   (127.088168, 37.528348), (127.059480, 37.533899)])


# 자양동의 경계를 Polygon으로 표시합니다
folium.GeoJson(jayang_dong_polygon).add_to(m)

# MarkerCluster 객체를 생성합니다
marker_cluster = MarkerCluster()

# 마커 클릭 시 팝업에 위도와 경도 표시
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    popup_text = f"위도: {candidate['latitude']:.6f}, 경도: {candidate['longitude']:.6f}"
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon=folium.Icon(icon='cloud'),
        popup=popup_text
    ).add_to(m)

# MarkerCluster를 지도에 추가합니다
marker_cluster.add_to(m)


# 지도를 표시합니다
m

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import folium

def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    d = R * c
    return d
# 수요지점
df_demand=jayang

# 후보지점 (랜덤 생성)
np.random.seed(42)
df_candidates = pd.DataFrame({
    'latitude': np.random.uniform(37.528348, 37.542486, 100),
    'longitude': np.random.uniform(127.059480, 127.088168, 100)
})

k = 40
kmeans = KMeans(n_clusters=k, n_init=20, random_state=0).fit(df_demand[['위도', '경도']])
centers = kmeans.cluster_centers_


selected_candidates_idx = []
unused_candidate_idxs = set(df_candidates.index)  # 사용하지 않은 후보지점의 인덱스를 저장하는 집합

for center in centers:
    closest_distance = np.inf
    closest_idx = None
    for idx in unused_candidate_idxs:  # 사용되지 않은 후보지점만 고려
        candidate = df_candidates.loc[idx]
        distance = haversine(center[0], center[1], candidate['latitude'], candidate['longitude'])
        if distance < closest_distance:
            closest_distance = distance
            closest_idx = idx

    if closest_idx is not None:  # 가장 가까운 후보지점을 찾았다면
        selected_candidates_idx.append(closest_idx)
        unused_candidate_idxs.remove(closest_idx)  # 선택된 후보지점을 사용된 것으로 표시

map_center_latitude = df_demand.iloc[0]['위도']
map_center_longitude = df_demand.iloc[0]['경도']
m = folium.Map(location=[map_center_latitude, map_center_longitude], zoom_start=12)


# 선택된 후보지 시각화 - 별 모양으로
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon = folium.Icon(icon='cloud')
    ).add_to(m)




import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon

# 자양동
jayang_dong_polygon = Polygon([(127.064266, 37.542486), (127.083535, 37.536838),
                                   (127.088168, 37.528348), (127.059480, 37.533899)])


# 자양동의 경계를 Polygon으로 표시합니다
folium.GeoJson(jayang_dong_polygon).add_to(m)

# MarkerCluster 객체를 생성합니다
marker_cluster = MarkerCluster()

# 마커 클릭 시 팝업에 위도와 경도 표시
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    popup_text = f"위도: {candidate['latitude']:.6f}, 경도: {candidate['longitude']:.6f}"
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon=folium.Icon(icon='cloud'),
        popup=popup_text
    ).add_to(m)

# MarkerCluster를 지도에 추가합니다
marker_cluster.add_to(m)


# 지도를 표시합니다
m

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import folium
import geopandas as gpd
import shapefile
import folium
import pandas as pd
from shapely.geometry import Point

def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    d = R * c
    return d
# 수요지점
df_demand=jayang

# 후보지점 (랜덤 생성)
np.random.seed(42)
df_candidates = pd.DataFrame({
    'latitude': np.random.uniform(37.528348, 37.542486, 100),
    'longitude': np.random.uniform(127.059480, 127.088168, 100)
})

k = 40
kmeans = KMeans(n_clusters=k, n_init=20, random_state=0).fit(df_demand[['위도', '경도']])
centers = kmeans.cluster_centers_


selected_candidates_idx = []
unused_candidate_idxs = set(df_candidates.index)  # 사용하지 않은 후보지점의 인덱스를 저장하는 집합

for center in centers:
    closest_distance = np.inf
    closest_idx = None
    for idx in unused_candidate_idxs:  # 사용되지 않은 후보지점만 고려
        candidate = df_candidates.loc[idx]
        distance = haversine(center[0], center[1], candidate['latitude'], candidate['longitude'])
        if distance < closest_distance:
            closest_distance = distance
            closest_idx = idx

    if closest_idx is not None:  # 가장 가까운 후보지점을 찾았다면
        selected_candidates_idx.append(closest_idx)
        unused_candidate_idxs.remove(closest_idx)  # 선택된 후보지점을 사용된 것으로 표시

map_center_latitude = df_demand.iloc[0]['위도']
map_center_longitude = df_demand.iloc[0]['경도']
m = folium.Map(location=[map_center_latitude, map_center_longitude], zoom_start=12)


# 수요 지점 시각화
for idx, row in df_demand.iterrows():
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=5,
        color='blue',
        fill=True,
        fill_color='blue'
    ).add_to(m)

# 선택된 후보지 시각화 - 별 모양으로
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon = folium.Icon(icon='cloud')
    ).add_to(m)

# 모든 후보지 시각화
for idx, candidate in df_candidates.iterrows():
    folium.CircleMarker(
        location=[candidate['latitude'], candidate['longitude']],
        radius=5,
        color='red',
        fill=True,
        fill_color='red'
    ).add_to(m)




import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon

# 자양동
jayang_dong_polygon = Polygon([(127.064266, 37.542486), (127.083535, 37.536838),
                                   (127.088168, 37.528348), (127.059480, 37.533899)])


# 자양동의 경계를 Polygon으로 표시합니다
folium.GeoJson(jayang_dong_polygon).add_to(m)

# MarkerCluster 객체를 생성합니다
marker_cluster = MarkerCluster()

# 마커 클릭 시 팝업에 위도와 경도 표시
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    popup_text = f"위도: {candidate['latitude']:.6f}, 경도: {candidate['longitude']:.6f}"
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon=folium.Icon(icon='cloud'),
        popup=popup_text
    ).add_to(m)

m


smoking = gpd.read_file('/content/drive/MyDrive/EGG_광진/데이터/흡연구역/흡연구역공간정보/흡연구역.shp')
non_smoking = gpd.read_file('/content/drive/MyDrive/EGG_광진/데이터/금연구역/금연구역공간정보/금연구역.shp')
non_smoking_p = gpd.read_file('/content/drive/MyDrive/EGG_광진/데이터/금연구역/금연구역공간정보/금연시설.shp')
# 흡연구역 표시
folium.GeoJson(
    smoking,
    style_function=lambda feature: {
        'fillColor': 'orange',# 채우기 색상
        'color': 'orange',       # 테두리 색상
        'weight': 2            # 테두리 두께
    }
).add_to(m)
# 금연구역 표시
folium.GeoJson(
    non_smoking,
    style_function=lambda feature: {
        'fillColor': 'orange',  # 채우기 색상
        'color': 'orange',       # 테두리 색상
        'weight': 2            # 테두리 두께
    }
).add_to(m)
#folium.GeoJson(non_smoking_p).add_to(m)
# CircleMarker를 사용하여 c를 지도에 추가
for idx, row in non_smoking_p.iterrows():
    # CircleMarker를 생성하고 해당 위치에 추가
    folium.CircleMarker(location=[row.geometry.y, row.geometry.x], radius=1, color='orange', fill=True).add_to(m)

#지도에 표시합니다
m

for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    print(f"위도: {candidate['latitude']:.6f}, 경도: {candidate['longitude']:.6f}")

"""여기서
자양동 최적 입지에서 제거할 입지
위도: 37.528987, 경도: 127.066297
위도: 37.532007, 경도: 127.067652
위도: 37.538663, 경도: 127.082924
위도: 37.533026, 경도: 127.086008
위도: 37.529729, 경도: 127.079648
위도: 37.532755, 경도: 127.076967
위도: 37.532184, 경도: 127.077620
위도: 37.536998, 경도: 127.082644
위도: 37.530941, 경도: 127.084480
위도: 37.533528, 경도: 127.062637
이 부분은 수동으로 제거
"""

import folium

# 주어진 위경도 리스트
coordinates = [
    (37.536937, 127.071455),
    (37.535738, 127.080306),
    (37.539689, 127.064831),
    (37.535767, 127.064832),
    (37.536283, 127.077642),
    (37.538697, 127.068498),
    (37.532478, 127.068603),
    (37.538342, 127.077989),
    (37.532465, 127.074953),
    (37.537160, 127.062735),
    (37.539307, 127.066353),
    (37.532948, 127.080371),
    (37.541381, 127.066424),
    (37.535349, 127.066703),
    (37.537362, 127.075408),
    (37.533392, 127.074850),
    (37.532945, 127.078414),
    (37.533843, 127.070031),
    (37.536812, 127.074070),
    (37.532649, 127.082536),
    (37.539449, 127.071733),
    (37.535329, 127.069498),
    (37.535618, 127.084173),
    (37.529873, 127.081853),
    (37.539248, 127.069206),
    (37.541204, 127.068112),
    (37.536021, 127.083443),
    (37.535024, 127.066418),
    (37.536847, 127.066044),
    (37.532745, 127.066880)
]


# 자양동
jayang_dong_polygon = Polygon([(127.064266, 37.542486), (127.083535, 37.536838),
                                   (127.088168, 37.528348), (127.059480, 37.533899)])

# 코랩에 지도를 표시합니다
m = folium.Map(location=[37.543170, 127.073432], zoom_start=13)

# 양동의 경계를 Polygon으로 표시합니다
folium.GeoJson(jayang_dong_polygon).add_to(m)

smoking = gpd.read_file('/content/drive/MyDrive/공모전/광진구 데이터분석/흡연구역.shp')
non_smoking = gpd.read_file('/content/drive/MyDrive/공모전/광진구 데이터분석/금연구역.shp')
non_smoking_p = gpd.read_file('/content/drive/MyDrive/공모전/광진구 데이터분석/금연시설.shp')

folium.GeoJson(smoking).add_to(m)
folium.GeoJson(non_smoking).add_to(m)
#folium.GeoJson(non_smoking_p).add_to(m)
# CircleMarker를 사용하여 c를 지도에 추가
for idx, row in non_smoking_p.iterrows():
    # CircleMarker를 생성하고 해당 위치에 추가
    folium.CircleMarker(location=[row.geometry.y, row.geometry.x], radius=1, color='blue', fill=True).add_to(m)

m


# MarkerCluster를 지도에 추가합니다
marker_cluster.add_to(m)


# 위치들을 지도에 마커로 표시
for coord in coordinates:
    latitude, longitude = coord
    popup_text = f"위도: {latitude:.6f}, 경도: {longitude:.6f}"
    folium.Marker(
        location=[latitude, longitude],
        icon=folium.Icon(color='blue'),
        popup=popup_text
    ).add_to(m)

# 지도를 표시
m

import folium

# 주어진 위경도 리스트
coordinates = [
    (37.536937, 127.071455),
    (37.535738, 127.080306),
    (37.539689, 127.064831),
    (37.535767, 127.064832),
    (37.536283, 127.077642),
    (37.538697, 127.068498),
    (37.532478, 127.068603),
    (37.538342, 127.077989),
    (37.532465, 127.074953),
    (37.537160, 127.062735),
    (37.539307, 127.066353),
    (37.532948, 127.080371),
    (37.541381, 127.066424),
    (37.535349, 127.066703),
    (37.537362, 127.075408),
    (37.533392, 127.074850),
    (37.532945, 127.078414),
    (37.533843, 127.070031),
    (37.536812, 127.074070),
    (37.532649, 127.082536),
    (37.539449, 127.071733),
    (37.535329, 127.069498),
    (37.535618, 127.084173),
    (37.529873, 127.081853),
    (37.539248, 127.069206),
    (37.541204, 127.068112),
    (37.536021, 127.083443),
    (37.535024, 127.066418),
    (37.536847, 127.066044),
    (37.532745, 127.066880)
]


# 자양동
jayang_dong_polygon = Polygon([(127.064266, 37.542486), (127.083535, 37.536838),
                                   (127.088168, 37.528348), (127.059480, 37.533899)])

# 코랩에 지도를 표시합니다
m = folium.Map(location=[37.543170, 127.073432], zoom_start=13)

# 양동의 경계를 Polygon으로 표시합니다
folium.GeoJson(jayang_dong_polygon).add_to(m)



# MarkerCluster를 지도에 추가합니다
marker_cluster.add_to(m)


# 위치들을 지도에 마커로 표시
for coord in coordinates:
    latitude, longitude = coord
    popup_text = f"위도: {latitude:.6f}, 경도: {longitude:.6f}"
    folium.Marker(
        location=[latitude, longitude],
        icon=folium.Icon(color='blue'),
        popup=popup_text
    ).add_to(m)

# 지도를 표시
m

"""자양동 최종 30곳 입지 선정 완료"""