# -*- coding: utf-8 -*-
"""광진구_구의동_최종코드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT2RpS1k8q3bN1K8btFMfuux9clv9SYs
"""

!pip install haversine
!pip install -U googlemaps
!pip install folium

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import folium

data = pd.read_csv('/content/drive/MyDrive/EGG_광진/코드/서울시 광진구 일반음식점 인허가 정보.csv', encoding='cp949')
print(data.head())

data1 = data[data['상세영업상태코드'] == 1]
data1

for i in range(data1.shape[0]):
    print(data1.iloc[i]['지번주소'], data1.iloc[i]['좌표정보(X)'], data1.iloc[i]['좌표정보(Y)'])

import folium

# 위도
latitude = 37.55573889
# 경도
longitude = 127.0845333
m = folium.Map(location=[latitude, longitude],
               zoom_start=13,
               width=750,
               height=500
              )
m

import pandas as pd
import numpy as np
import pyproj

data1['좌표정보(X)'] = pd.to_numeric(data1['좌표정보(X)'], errors="coerce")
data1['좌표정보(Y)'] = pd.to_numeric(data1['좌표정보(Y)'], errors="coerce")

data1.dropna(subset=['좌표정보(X)', '좌표정보(Y)'], inplace=True)
data1.index = range(len(data1))

def project_array(coord, p1_type, p2_type):
    """
    좌표계 변환 함수
    - coord: x, y 좌표 정보가 담긴 NumPy Array
    - p1_type: 입력 좌표계 정보 ex) epsg:5174
    - p2_type: 출력 좌표계 정보 ex) epsg:3857
    """
    p1 = pyproj.Proj(init=p1_type)
    p2 = pyproj.Proj(init=p2_type)
    fx, fy = pyproj.transform(p1, p2, coord[:, 0], coord[:, 1])
    return np.dstack([fx, fy])[0]

coord = np.array(data1[['좌표정보(X)', '좌표정보(Y)']])
print(coord)

# 컬럼 좌표(X) 또는 좌표(Y) 중의 값이 하나라도 없으면 변환이 안 되는 조건 추가
if len(coord) == 0:
    print("No valid coordinates found. Transformation cannot be performed.")
else:
    # 좌표계 정보 설정
    p1_type = "epsg:5174"
    p2_type = "epsg:3857"

    # project_array() 함수 실행
    result = project_array(coord, p1_type, p2_type)
    print(result)

    data1['경도X'] = result[:, 0]
    data1['위도Y'] = result[:, 1]

    data1.tail()

    output_file = '/content/drive/MyDrive/EGG_광진/서울시 광진구 일반음식점 인허가 정보_1.csv'
    data1.to_csv(output_file, index=False, encoding='utf-8')

df = pd.read_csv('/content/drive/MyDrive/EGG_광진/서울시 광진구 일반음식점 인허가 정보_1.csv', encoding='utf-8')

df['경도X'] = pd.to_numeric(df['경도X'], errors="coerce")
df['위도Y'] = pd.to_numeric(df['위도Y'], errors="coerce")

df.dropna(subset=['경도X', '위도Y'], inplace=True)
df.index = range(len(df))

def project_array(coord, p1_type, p2_type):
    """
    좌표계 변환 함수
    - coord: x, y 좌표 정보가 담긴 NumPy Array
    - p1_type: 입력 좌표계 정보 ex) epsg:4326
    - p2_type: 출력 좌표계 정보 ex) epsg:3857
    """
    p1 = pyproj.Proj(init=p1_type)
    p2 = pyproj.Proj(init=p2_type)
    fx, fy = pyproj.transform(p1, p2, coord[:, 0], coord[:, 1])
    return np.dstack([fx, fy])[0]

coord = np.array(df[['경도X', '위도Y']])
print(coord)

# 컬럼 좌표(X) 또는 좌표(Y) 중의 값이 하나라도 없으면 변환이 안 되는 조건 추가
if len(coord) == 0:
    print("No valid coordinates found. Transformation cannot be performed.")
else:
    # 좌표계 정보 설정
    p1_type = "EPSG:3857"
    p2_type = "EPSG:4326"

    # project_array() 함수 실행
    result = project_array(coord, p1_type, p2_type)
    print(result)

    df['경도'] = result[:, 0]
    df['위도'] = result[:, 1]

    df.tail()

    output_file = '/content/drive/MyDrive/EGG_광진/서울시 광진구 일반음식점 인허가 정보_2.csv.csv'
    df.to_csv(output_file, index=False, encoding='utf-8')

df.head()

df2 = df.copy()
df2 = df2[['지번주소', '위도', '경도']]


# 서울특별시 광진구 제거
df2['지번주소'] = df2['지번주소'].str.replace('서울특별시 광진구', '')

# 특수문자 ('-') 제거
df2['지번주소'] = df2['지번주소'].str.replace(pat = r'[^\w]', repl = r'', regex = True)

# 숫자 제거
df2['지번주소'] = df2['지번주소'].str.replace(pat = r"[0-9]+", repl = r'', regex = True)

# '동' 제외 문자 제거
r = r'(?<=동).*$'
df2['지번주소'] = df2['지번주소'].str.replace(pat = r, repl = '', regex = True)

# 공백 제거 확인
df2['지번주소'] = df2['지번주소'].replace(r'^\s+|\s+$', '', regex = True)

df2

guui= df2[df2['지번주소'] == '구의동']
guui

import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon

# 구의동
guui_dong_polygon = Polygon([(127.092000, 37.531129), (127.099635, 37.538013),
                                   (127.085474, 37.549835), (127.079079, 37.545547)])

# 코랩에 지도를 표시합니다
m = folium.Map(location=[37.543170, 127.073432], zoom_start=13)

# 구의동의 경계를 Polygon으로 표시합니다
folium.GeoJson(guui_dong_polygon).add_to(m)

# MarkerCluster 객체를 생성합니다
marker_cluster = MarkerCluster()

# 구의동을 중심으로 마커를 추가합니다
folium.Marker([37.541134, 127.088547], popup="구의동").add_to(marker_cluster)

# MarkerCluster를 지도에 추가합니다
marker_cluster.add_to(m)


for i in guui.index[::]:
    folium.Circle(
        location = guui.loc[i, ['위도', '경도']],
        tooltip = guui.loc[i, '지번주소'],
        radius = 1
    ).add_to(m)


# 지도를 표시합니다
m

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import folium

def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    d = R * c
    return d

# 수요지점
df_demand=guui

# 후보지점 (랜덤 생성)
np.random.seed(42)
df_candidates = pd.DataFrame({
    'latitude': np.random.uniform(37.531129, 37.549835, 100),
    'longitude': np.random.uniform(127.079079,127.099635, 100)
})

k = 40
kmeans = KMeans(n_clusters=k, n_init=20, random_state=0).fit(df_demand[['위도', '경도']])
centers = kmeans.cluster_centers_


selected_candidates_idx = []
unused_candidate_idxs = set(df_candidates.index)  # 사용하지 않은 후보지점의 인덱스를 저장하는 집합

for center in centers:
    closest_distance = np.inf
    closest_idx = None
    for idx in unused_candidate_idxs:  # 사용되지 않은 후보지점만 고려
        candidate = df_candidates.loc[idx]
        distance = haversine(center[0], center[1], candidate['latitude'], candidate['longitude'])
        if distance < closest_distance:
            closest_distance = distance
            closest_idx = idx

    if closest_idx is not None:  # 가장 가까운 후보지점을 찾았다면
        selected_candidates_idx.append(closest_idx)
        unused_candidate_idxs.remove(closest_idx)  # 선택된 후보지점을 사용된 것으로 표시

map_center_latitude = df_demand.iloc[0]['위도']
map_center_longitude = df_demand.iloc[0]['경도']
m = folium.Map(location=[map_center_latitude, map_center_longitude], zoom_start=12)

# 수요 지점 시각화
for idx, row in df_demand.iterrows():
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=5,
        color='blue',
        fill=True,
        fill_color='blue'
    ).add_to(m)

# 선택된 후보지 시각화 - 별 모양으로
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon = folium.Icon(icon='cloud')
    ).add_to(m)

# 모든 후보지 시각화
for idx, candidate in df_candidates.iterrows():
    folium.CircleMarker(
        location=[candidate['latitude'], candidate['longitude']],
        radius=5,
        color='red',
        fill=True,
        fill_color='red'
    ).add_to(m)


import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon


# 구의동
guui_dong_polygon = Polygon([(127.092000, 37.531129), (127.099635, 37.538013),
                                   (127.085474, 37.549835), (127.079079, 37.545547)])

# 구의동의 경계를 Polygon으로 표시합니다
folium.GeoJson(guui_dong_polygon).add_to(m)

# MarkerCluster 객체를 생성합니다
marker_cluster = MarkerCluster()



# MarkerCluster를 지도에 추가합니다
marker_cluster.add_to(m)


# 지도를 표시합니다
m

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import folium
import geopandas as gpd
import shapefile
import pandas as pd
from shapely.geometry import Point

def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    d = R * c
    return d

# 수요지점
df_demand=guui

# 후보지점 (랜덤 생성)
np.random.seed(42)
df_candidates = pd.DataFrame({
    'latitude': np.random.uniform(37.531129, 37.549835, 100),
    'longitude': np.random.uniform(127.079079,127.099635, 100)
})

k = 40
kmeans = KMeans(n_clusters=k, n_init=20, random_state=0).fit(df_demand[['위도', '경도']])
centers = kmeans.cluster_centers_


selected_candidates_idx = []
unused_candidate_idxs = set(df_candidates.index)  # 사용하지 않은 후보지점의 인덱스를 저장하는 집합

for center in centers:
    closest_distance = np.inf
    closest_idx = None
    for idx in unused_candidate_idxs:  # 사용되지 않은 후보지점만 고려
        candidate = df_candidates.loc[idx]
        distance = haversine(center[0], center[1], candidate['latitude'], candidate['longitude'])
        if distance < closest_distance:
            closest_distance = distance
            closest_idx = idx

    if closest_idx is not None:  # 가장 가까운 후보지점을 찾았다면
        selected_candidates_idx.append(closest_idx)
        unused_candidate_idxs.remove(closest_idx)  # 선택된 후보지점을 사용된 것으로 표시

map_center_latitude = df_demand.iloc[0]['위도']
map_center_longitude = df_demand.iloc[0]['경도']
m = folium.Map(location=[map_center_latitude, map_center_longitude], zoom_start=12)

# 수요 지점 시각화
for idx, row in df_demand.iterrows():
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=5,
        color='blue',
        fill=True,
        fill_color='blue'
    ).add_to(m)

# 선택된 후보지 시각화 - 별 모양으로
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon = folium.Icon(icon='cloud')
    ).add_to(m)

# 모든 후보지 시각화
for idx, candidate in df_candidates.iterrows():
    folium.CircleMarker(
        location=[candidate['latitude'], candidate['longitude']],
        radius=5,
        color='red',
        fill=True,
        fill_color='red'
    ).add_to(m)


import folium
from folium.plugins import MarkerCluster
from shapely.geometry import Polygon

# 구의동
guui_dong_polygon = Polygon([(127.092000, 37.531129), (127.099635, 37.538013),
                                   (127.085474, 37.549835), (127.079079, 37.545547)])

# 구의동의 경계를 Polygon으로 표시합니다
folium.GeoJson(guui_dong_polygon).add_to(m)

# MarkerCluster 객체를 생성합니다
marker_cluster = MarkerCluster()

# 마커 클릭 시 팝업에 위도와 경도 표시
for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    popup_text = f"위도: {candidate['latitude']:.6f}, 경도: {candidate['longitude']:.6f}"
    folium.Marker(
        location=[candidate['latitude'], candidate['longitude']],
        icon=folium.Icon(icon='cloud'),
        popup=popup_text
    ).add_to(m)


# MarkerCluster를 지도에 추가합니다
marker_cluster.add_to(m)



smoking = gpd.read_file('/content/drive/MyDrive/EGG_광진/데이터/흡연구역/흡연구역공간정보/흡연구역.shp')
non_smoking = gpd.read_file('/content/drive/MyDrive/EGG_광진/데이터/금연구역/금연구역공간정보/금연구역.shp')
non_smoking_p = gpd.read_file('/content/drive/MyDrive/EGG_광진/데이터/금연구역/금연구역공간정보/금연시설.shp')

# 흡연구역 표시
folium.GeoJson(
    smoking,
    style_function=lambda feature: {
        'fillColor': 'orange',# 채우기 색상
        'color': 'orange',       # 테두리 색상
        'weight': 2            # 테두리 두께
    }
).add_to(m)
# 금연구역 표시
folium.GeoJson(
    non_smoking,
    style_function=lambda feature: {
        'fillColor': 'orange',  # 채우기 색상
        'color': 'orange',       # 테두리 색상
        'weight': 2            # 테두리 두께
    }
).add_to(m)
#folium.GeoJson(non_smoking_p).add_to(m)
# CircleMarker를 사용하여 c를 지도에 추가
for idx, row in non_smoking_p.iterrows():
    # CircleMarker를 생성하고 해당 위치에 추가
    folium.CircleMarker(location=[row.geometry.y, row.geometry.x], radius=1, color='orange', fill=True).add_to(m)

#지도에 표시합니다
m

"""위도: 37.542494, 경도: 127.087659/위도: 37.537212, 경도: 127.092646/위도: 37.536205, 경도: 127.092077/위도: 37.537215, 경도: 127.094048/위도: 37.534795, 경도: 127.094735/위도: 37.535101, 경도: 127.095691//위도: 37.542211, 경도: 127.079222/위도: 37.535970, 경도: 127.084934/위도: 37.536594, 경도: 127.085616/위도: 37.536946, 경도: 127.084381/위도: 37.539660, 경도: 127.083764/위도: 37.540748, 경도: 127.096772/위도: 37.544351, 경도: 127.092341/위도: 37.547332, 경도: 127.094610/위도: 37.549192, 경도: 127.098461/위도: 37.549266, 경도: 127.097749/위도: 37.546631, 경도: 127.092102/위도: 37.548913, 경도: 127.092161/위도: 37.547725, 경도: 127.089966/위도: 37.547868, 경도: 127.089140/위도: 37.549590, 경도: 127.091225//////총 21군데 제외,(// 이후는 경계 밖) 19군데 입지 선정.

"""

for idx in selected_candidates_idx:
    candidate = df_candidates.iloc[idx]
    print(f"위도: {candidate['latitude']:.6f}, 경도: {candidate['longitude']:.6f}")

import folium

# 주어진 위경도 리스트
coordinates = [

(37.545817, 127.087859),
(37.538400, 127.086639),
(37.544766, 127.082663),
(37.534530,127.092099),
(37.542373,127.083782),
(37.540907,127.094002),
(37.543055,127.090492),
(37.537802, 127.090092),
(37.539962, 127.084051),
(37.542328,127.089533),
(37.543928,127.086554),
(37.537319, 127.098087),
(37.541628, 127.092093),
(37.540857, 127.089412),
(37.539962, 127.084051),
(37.545551, 127.086048),
(37.540366,  127.086257),
(37.546251, 127.085723),
(37.548879, 127.086019)
]



# 구의동
guui_dong_polygon = Polygon([(127.092000, 37.531129), (127.099635, 37.538013),
                                   (127.085474, 37.549835), (127.079079, 37.545547)])


m = folium.Map(location=[map_center_latitude, map_center_longitude], zoom_start=12)

# 구의동의 경계를 Polygon으로 표시합니다
folium.GeoJson(guui_dong_polygon).add_to(m)





# 위치들을 지도에 마커로 표시
for coord in coordinates:
    latitude, longitude = coord
    popup_text = f"위도: {latitude:.6f}, 경도: {longitude:.6f}"
    folium.Marker(
        location=[latitude, longitude],
        icon=folium.Icon(color='blue'),
        popup=popup_text
    ).add_to(m)

# 지도를 표시
m